site_name: laminsoft
theme:
  name: material

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https
    - icon: fontawesome/brands/twitter
      link: https
    - icon: fontawesome/brands/linkedin
      link: https
markdown_extensions:
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="http://" target="_blank" rel="noopener">Damin Haidar</a>
